{"abstract":[{"type":"text","text":"A description of the error, suitable for displaying to the user."}],"hierarchy":{"paths":[["doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/AuthError"]]},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"inlineContent":[{"type":"text","text":"This property provides a localized description for each error case, making it easier to"},{"text":" ","type":"text"},{"text":"understand what went wrong during the authentication process.","type":"text"}],"type":"paragraph"}]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"roleHeading":"Instance Property","modules":[{"name":"MDots"}],"title":"errorDescription","externalID":"s:5MDots9AuthErrorO16errorDescriptionSSSgvp","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"errorDescription"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","symbolKind":"property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdots\/autherror\/errordescription"]}],"identifier":{"url":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/AuthError\/errorDescription","interfaceLanguage":"swift"},"references":{"doc://com.estelapasjak.Mdots/documentation/MDots/AuthError":{"role":"symbol","url":"\/documentation\/mdots\/autherror","title":"AuthError","abstract":[{"type":"text","text":"An enumeration representing various authentication errors that can occur."}],"identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/AuthError","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AuthError","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AuthError"}],"kind":"symbol"},"doc://com.estelapasjak.Mdots/documentation/MDots/AuthError/errorDescription":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorDescription","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/AuthError\/errorDescription","kind":"symbol","title":"errorDescription","abstract":[{"type":"text","text":"A description of the error, suitable for displaying to the user."}],"url":"\/documentation\/mdots\/autherror\/errordescription","role":"symbol"},"doc://com.estelapasjak.Mdots/documentation/MDots":{"images":[{"type":"icon","identifier":"appIcon.png"}],"type":"topic","title":"MDots","role":"collection","url":"\/documentation\/mdots","identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots","kind":"symbol","abstract":[]},"appIcon.png":{"identifier":"appIcon.png","type":"image","alt":"The logo representing the MDot sensor application.","variants":[{"traits":["1x","light"],"url":"\/images\/appIcon.png"}]}}}